name: CI
on:
    push:
        branches:
            - main
env:
    BUILD_NUMBER: ${{ github.run_number }}
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                context: .
                file: ../Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/e-dukan-ui:${{ github.run_number }}
              env:
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
